wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/01001.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/01004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/01028.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/01152.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/01241.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/01384.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/01400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/01415.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/02185.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/02225.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/02365.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/02527.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/02591.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/02836.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/02935.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/02963.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03005.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03023.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03026.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03091.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03170.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03213.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03257.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03322.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03354.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03496.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03502.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03693.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03743.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03774.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03808.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03882.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03920.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/03953.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/04018.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/04202.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/04220.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/04270.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/04310.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/04320.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/04339.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/04360.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06011.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06030.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06060.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06181.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06210.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06260.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06447.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06476.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06496.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/06610.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/07110.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/07145.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/07180.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/07481.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/07510.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/07645.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/07761.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08001.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08023.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08160.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08221.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08301.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08430.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08495.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08508.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08521.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08522.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08579.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/08594.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10046.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10184.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10200.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10238.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10304.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10307.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10338.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10384.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10393.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10410.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10437.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10454.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10486.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10513.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10548.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10618.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10642.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10687.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10739.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10771.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10828.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10868.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/10962.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/11010.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/11035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/11120.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/11240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/11520.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/11722.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/11952.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/12105.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/12120.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/12330.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/12374.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/12425.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/12843.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/12982.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/13275.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/13586.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/14015.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/14240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/15120.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/15420.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/15480.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/15614.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/15730.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16044.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16080.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16144.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16242.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16245.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16320.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16429.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16560.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16597.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16622.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16716.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/16754.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17030.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17062.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17130.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17220.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17280.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17351.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17601.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17606.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/17607.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20046.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20069.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20107.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20274.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20292.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20353.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20667.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20674.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20744.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/20891.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/21358.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/21432.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/21504.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/21647.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/21824.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/21946.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/21965.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/21982.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/22113.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/22217.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/22271.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/22522.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/22550.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/22802.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/22820.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/22845.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23022.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23078.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23146.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23205.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23274.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23330.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23418.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23472.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23552.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23804.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23884.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23921.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23933.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/23955.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24125.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24266.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24343.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24507.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24641.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24688.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24726.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24790.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24817.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24908.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24944.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/24959.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25042.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25123.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25173.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25399.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25428.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25551.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25563.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25594.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25677.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25703.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25822.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25913.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/25954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26038.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26063.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26258.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26298.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26406.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26422.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26477.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26629.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26702.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26781.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/26850.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27037.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27199.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27459.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27595.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27707.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27730.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27944.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27962.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/27995.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/28225.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/28275.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/28440.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/28445.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/28661.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/28698.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/28722.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/28900.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/28952.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29231.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29263.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29282.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29572.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29574.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29634.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29698.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29838.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/29862.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30054.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30230.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30309.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30372.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30521.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30554.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30635.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30673.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30692.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30710.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30715.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30758.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30935.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/30965.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31088.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31168.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31300.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31329.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31369.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31510.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31538.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31561.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31707.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31736.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31770.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31873.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31909.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31960.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/31977.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32061.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32098.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32099.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32150.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32165.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32186.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32215.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32217.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32389.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32477.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32540.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/32618.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33008.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33041.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33317.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33345.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33393.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33631.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33658.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33791.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33815.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33837.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/33946.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/34009.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/34122.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/34172.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/34247.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/34300.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/34560.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/34731.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/34858.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/34880.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/35108.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/35121.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/35229.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/35361.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/35394.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/35671.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/35700.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/35746.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/35796.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/36003.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/36096.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/36177.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/36859.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/36870.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/36974.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/37018.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/37054.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/37260.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/37472.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/37484.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/37549.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/37789.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/37860.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/37985.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38062.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38341.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38353.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38392.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38413.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38457.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38507.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38613.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38687.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38750.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38836.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38880.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38927.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/38989.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40007.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40080.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40100.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40179.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40265.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40373.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40375.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40394.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40417.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40430.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40437.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40438.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40495.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40582.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40650.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40689.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40706.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40745.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40754.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40766.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40795.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40800.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40809.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40811.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40841.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40848.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40875.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40938.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40948.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/40990.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41024.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41112.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41114.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41217.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41256.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41288.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41316.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41404.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41480.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41530.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41594.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41640.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41661.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41675.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41756.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41780.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41883.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41923.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/41977.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42027.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42101.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42182.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42314.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42339.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42361.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42369.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42379.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42397.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42410.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42492.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42647.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42667.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42701.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42724.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42809.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42867.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42874.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/42971.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43003.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43014.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43041.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43128.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43150.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43185.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43192.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43279.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43285.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43295.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43311.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43333.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43346.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43353.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43369.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43371.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43466.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43555.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/43599.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/44212.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/44231.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/44259.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/44277.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/44288.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/44292.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/44354.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/44373.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/45004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/46750.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/46780.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47058.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47122.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47138.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47158.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47185.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47401.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47412.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47420.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47580.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47582.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47590.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47600.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47646.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47678.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47681.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47744.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47778.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47807.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47827.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47881.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47909.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47918.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47936.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47945.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47971.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47981.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/47991.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48042.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48053.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48062.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48097.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48327.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48354.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48407.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48455.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48565.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48568.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48601.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48615.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48647.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48657.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48698.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48820.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48855.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/48900.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/50527.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/50557.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/50745.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/50774.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/50834.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/50953.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51076.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51133.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51243.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51288.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51431.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51463.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51628.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51644.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51656.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51709.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51777.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51828.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51839.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51848.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/51886.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52267.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52323.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52418.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52495.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52533.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52602.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52652.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52681.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52818.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52836.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52866.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/52889.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53068.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53336.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53463.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53513.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53543.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53614.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53772.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53798.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53845.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/53915.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54102.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54135.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54161.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54218.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54292.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54337.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54342.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54374.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54401.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54497.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54511.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54662.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54776.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54823.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/54857.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/55299.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/55591.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/55664.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56029.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56046.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56080.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56096.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56137.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56146.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56173.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56247.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56294.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56312.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56492.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56571.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56651.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56691.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56739.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56778.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56964.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56985.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/56989.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57036.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57083.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57127.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57178.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57245.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57328.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57447.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57461.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57494.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57516.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57679.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57749.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57816.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57957.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57972.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/57993.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58027.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58150.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58238.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58362.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58367.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58424.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58457.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58606.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58633.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58665.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58666.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58725.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/58847.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59023.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59096.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59134.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59211.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59265.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59280.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59287.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59316.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59431.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59644.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59663.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59758.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59948.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/59981.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60018.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60020.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60155.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60191.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60252.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60390.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60490.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60525.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60549.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60550.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60571.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60580.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60611.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60630.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60656.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60680.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60715.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/60760.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61024.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61052.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61202.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61223.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61291.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61415.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61442.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61641.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61687.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61831.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61901.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61902.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61967.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61976.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61980.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61995.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61996.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/61998.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62010.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62019.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62053.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62062.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62103.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62124.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62271.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62306.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62337.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62378.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62414.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62423.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/62721.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63021.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63450.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63478.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63705.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63723.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63741.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63832.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63894.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/63985.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/64400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/64458.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/64500.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/64650.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/64700.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/64870.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/64910.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/65046.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/65123.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/65202.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/65330.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/65344.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/65418.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/65503.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/65555.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/65578.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/66160.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/66422.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/67083.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/67197.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/67237.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/67341.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/67586.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/67633.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/67666.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/67774.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/67964.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68014.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68032.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68040.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68110.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68112.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68174.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68263.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68312.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68328.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68406.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68424.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68442.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68461.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68512.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68538.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68588.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68816.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68842.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68906.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/68994.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70026.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70086.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70133.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70200.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70219.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70231.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70261.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70266.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70273.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70308.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70316.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70326.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70350.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70361.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70398.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70414.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/70454.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71043.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71072.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71081.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71082.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71109.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71115.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71119.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71124.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71600.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71603.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71625.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71701.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71716.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71722.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71801.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71811.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71815.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71816.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71823.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71826.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71836.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71845.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71848.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71853.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71867.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71876.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71877.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71906.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71907.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71908.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71909.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71913.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71915.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71917.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71924.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71925.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71926.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71934.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71945.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71957.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/71964.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72201.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72202.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72206.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72208.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72210.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72214.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72215.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72221.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72225.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72230.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72232.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72233.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72235.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72248.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72249.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72250.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72251.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72257.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72261.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72265.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72269.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72273.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72274.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72280.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72291.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72293.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72295.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72305.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72317.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72318.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72327.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72340.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72355.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72357.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72363.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72364.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72365.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72376.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72381.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72387.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72389.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72391.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72393.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72402.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72403.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72405.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72408.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72426.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72440.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72451.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72455.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72456.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72468.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72469.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72476.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72489.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72493.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72501.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72518.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72520.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72528.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72558.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72562.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72572.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72582.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72597.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72632.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72634.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72645.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72649.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72659.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72662.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72672.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72681.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72694.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72698.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72712.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72747.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72764.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72768.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72776.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72786.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72793.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72797.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/72938.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74002.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74051.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74074.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74090.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74207.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74389.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74455.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74486.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74494.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74530.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74547.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74560.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74606.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74626.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74641.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74646.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74650.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74651.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/74794.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76151.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76225.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76256.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76382.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76394.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76405.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76458.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76595.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76644.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76654.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76679.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76692.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76723.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/76805.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78016.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78073.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78118.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78325.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78355.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78367.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78384.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78397.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78486.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78501.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78526.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78583.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78720.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78730.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78762.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78806.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78861.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78866.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78897.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78970.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/78988.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/80001.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/80035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/80222.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/80241.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/80398.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/80413.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/80447.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/80462.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/81405.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82193.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82280.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82332.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82397.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82599.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82678.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82765.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82824.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82900.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82965.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/82983.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83208.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83229.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83288.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83362.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83378.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83498.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83566.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83650.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83746.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83779.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83780.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83827.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83840.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83899.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/83971.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/84008.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/84203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/84628.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/85201.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/85442.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/85469.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/85543.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/85586.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/85799.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/85934.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/86218.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/87047.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/87155.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/87344.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/87418.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/87576.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/87623.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/87715.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/87748.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/87860.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/88889.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/88968.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89001.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89002.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89009.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89022.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89050.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89055.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89512.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89532.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89542.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89564.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89571.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89592.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89606.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89611.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89642.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89662.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89664.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/89671.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91066.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91165.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91212.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91245.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91275.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91285.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91334.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91348.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91366.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91376.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91408.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91413.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91517.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91557.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91592.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91610.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91643.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91680.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91701.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91765.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91801.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91843.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91925.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91938.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91943.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91944.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91948.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/91958.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/92035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/92044.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/93112.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/93417.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/93780.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/93844.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/93944.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/93986.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/93997.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94014.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94120.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94150.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94170.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94175.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94238.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94294.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94299.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94300.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94302.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94312.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94326.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94332.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94374.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94403.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94430.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94461.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94510.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94578.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94610.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94637.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94638.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94646.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94647.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94659.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94672.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94711.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94750.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94767.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94776.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94802.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94821.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94865.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94866.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94910.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94975.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94995.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94996.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/94998.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/95527.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96147.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96163.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96237.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96315.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96413.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96441.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96471.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96481.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96749.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96933.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96935.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/96996.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/97014.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/97072.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/97180.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/97372.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/97560.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/97724.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/97980.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/98223.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/98327.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/98444.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/98618.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/98646.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/98753.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/data-y2d/98836.dat.gz
