wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/01001.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/01004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/01028.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/01152.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/01241.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/01384.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/01400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/01415.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/02185.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/02225.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/02365.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/02527.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/02591.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/02836.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/02935.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/02963.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03005.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03023.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03026.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03091.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03170.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03213.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03257.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03322.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03354.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03496.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03502.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03693.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03743.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03774.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03808.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03882.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03920.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/03953.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/04018.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/04202.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/04220.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/04270.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/04310.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/04320.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/04339.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/04360.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06011.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06030.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06060.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06181.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06210.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06260.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06447.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06476.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06496.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/06610.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/07110.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/07145.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/07180.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/07481.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/07510.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/07645.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/07761.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08001.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08023.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08160.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08221.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08301.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08430.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08495.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08508.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08521.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08522.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08579.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/08594.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10046.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10184.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10200.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10238.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10304.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10307.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10338.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10384.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10393.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10410.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10437.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10454.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10486.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10513.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10548.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10618.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10642.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10687.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10739.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10771.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10828.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10868.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/10962.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/11010.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/11035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/11120.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/11240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/11520.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/11722.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/11952.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/12105.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/12120.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/12330.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/12374.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/12425.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/12843.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/12982.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/13275.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/13586.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/14015.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/14240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/15120.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/15420.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/15480.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/15614.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/15730.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16044.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16080.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16144.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16242.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16245.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16320.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16429.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16560.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16597.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16622.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16716.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/16754.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17030.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17062.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17130.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17220.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17280.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17351.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17601.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17606.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/17607.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20046.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20069.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20107.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20274.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20292.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20353.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20667.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20674.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20744.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/20891.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/21358.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/21432.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/21504.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/21647.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/21824.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/21946.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/21965.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/21982.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/22113.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/22217.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/22271.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/22522.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/22550.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/22802.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/22820.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/22845.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23022.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23078.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23146.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23205.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23274.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23330.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23418.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23472.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23552.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23804.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23884.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23921.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23933.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/23955.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24125.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24266.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24343.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24507.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24641.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24688.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24726.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24790.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24817.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24908.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24944.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/24959.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25042.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25123.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25173.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25399.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25428.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25551.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25563.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25594.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25677.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25703.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25822.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25913.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/25954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26038.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26063.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26258.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26298.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26406.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26422.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26477.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26629.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26702.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26781.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/26850.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27037.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27199.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27459.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27595.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27707.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27730.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27944.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27962.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/27995.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/28225.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/28275.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/28440.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/28445.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/28661.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/28698.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/28722.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/28900.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/28952.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29231.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29263.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29282.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29572.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29574.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29634.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29698.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29838.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/29862.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30054.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30230.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30309.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30372.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30521.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30554.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30635.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30673.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30692.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30710.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30715.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30758.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30935.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/30965.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31088.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31168.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31300.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31329.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31369.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31510.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31538.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31561.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31707.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31736.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31770.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31873.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31909.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31960.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/31977.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32061.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32098.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32099.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32150.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32165.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32186.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32215.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32217.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32389.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32477.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32540.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/32618.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33008.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33041.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33317.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33345.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33393.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33631.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33658.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33791.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33815.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33837.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/33946.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/34009.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/34122.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/34172.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/34247.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/34300.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/34560.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/34731.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/34858.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/34880.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/35108.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/35121.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/35229.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/35361.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/35394.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/35671.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/35700.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/35746.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/35796.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/36003.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/36096.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/36177.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/36859.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/36870.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/36974.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/37018.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/37054.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/37260.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/37472.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/37484.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/37549.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/37789.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/37860.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/37985.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38062.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38341.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38353.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38392.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38413.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38457.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38507.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38613.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38687.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38750.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38836.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38880.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38927.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/38989.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40007.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40080.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40100.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40179.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40265.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40373.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40375.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40394.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40417.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40430.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40437.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40438.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40495.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40582.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40650.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40689.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40706.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40745.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40754.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40766.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40795.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40800.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40809.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40811.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40841.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40848.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40875.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40938.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40948.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/40990.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41024.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41112.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41114.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41217.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41256.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41288.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41316.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41404.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41480.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41530.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41594.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41640.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41661.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41675.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41756.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41780.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41883.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41923.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/41977.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42027.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42101.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42182.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42314.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42339.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42361.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42369.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42379.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42397.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42410.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42492.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42647.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42667.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42701.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42724.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42809.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42867.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42874.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/42971.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43003.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43014.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43041.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43128.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43150.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43185.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43192.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43279.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43285.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43295.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43311.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43333.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43346.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43353.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43369.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43371.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43466.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43555.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/43599.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/44212.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/44231.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/44259.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/44277.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/44288.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/44292.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/44354.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/44373.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/45004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/46750.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/46780.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47058.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47122.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47138.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47158.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47185.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47401.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47412.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47420.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47580.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47582.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47590.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47600.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47646.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47678.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47681.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47744.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47778.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47807.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47827.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47881.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47909.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47918.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47936.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47945.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47971.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47981.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/47991.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48042.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48053.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48062.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48097.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48327.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48354.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48407.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48455.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48565.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48568.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48601.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48615.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48647.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48657.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48698.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48820.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48855.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/48900.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/50527.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/50557.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/50745.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/50774.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/50834.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/50953.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51076.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51133.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51243.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51288.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51431.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51463.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51628.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51644.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51656.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51709.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51777.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51828.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51839.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51848.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/51886.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52267.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52323.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52418.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52495.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52533.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52602.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52652.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52681.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52818.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52836.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52866.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/52889.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53068.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53336.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53463.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53513.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53543.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53614.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53772.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53798.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53845.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/53915.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54102.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54135.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54161.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54218.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54292.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54337.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54342.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54374.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54401.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54497.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54511.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54662.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54776.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54823.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/54857.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/55299.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/55591.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/55664.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56029.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56046.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56080.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56096.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56137.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56146.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56173.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56247.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56294.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56312.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56492.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56571.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56651.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56691.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56739.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56778.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56964.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56985.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/56989.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57036.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57083.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57127.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57178.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57245.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57328.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57447.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57461.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57494.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57516.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57679.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57749.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57816.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57957.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57972.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/57993.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58027.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58150.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58238.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58362.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58367.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58424.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58457.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58606.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58633.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58665.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58666.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58725.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/58847.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59023.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59096.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59134.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59211.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59265.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59280.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59287.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59316.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59431.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59644.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59663.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59758.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59948.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/59981.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60018.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60020.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60155.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60191.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60252.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60390.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60490.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60525.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60549.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60550.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60571.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60580.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60611.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60630.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60656.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60680.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60715.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/60760.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61024.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61052.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61202.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61223.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61291.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61415.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61442.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61641.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61687.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61831.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61901.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61902.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61967.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61976.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61980.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61995.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61996.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/61998.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62010.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62019.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62053.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62062.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62103.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62124.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62271.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62306.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62337.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62378.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62414.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62423.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/62721.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63021.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63450.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63478.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63705.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63723.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63741.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63832.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63894.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/63985.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/64400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/64458.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/64500.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/64650.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/64700.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/64870.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/64910.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/65046.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/65123.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/65202.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/65330.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/65344.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/65418.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/65503.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/65555.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/65578.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/66160.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/66422.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/67083.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/67197.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/67237.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/67341.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/67586.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/67633.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/67666.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/67774.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/67964.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68014.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68032.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68040.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68110.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68112.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68174.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68263.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68312.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68328.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68406.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68424.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68442.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68461.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68512.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68538.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68588.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68816.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68842.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68906.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/68994.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70026.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70086.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70133.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70200.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70219.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70231.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70261.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70266.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70273.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70308.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70316.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70326.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70350.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70361.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70398.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70414.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/70454.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71043.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71072.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71081.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71082.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71109.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71115.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71119.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71124.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71600.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71603.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71625.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71701.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71716.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71722.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71801.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71811.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71815.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71816.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71823.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71826.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71836.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71845.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71848.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71853.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71867.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71876.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71877.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71906.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71907.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71908.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71909.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71913.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71915.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71917.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71924.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71925.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71926.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71934.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71945.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71957.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/71964.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72201.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72202.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72206.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72208.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72210.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72214.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72215.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72221.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72225.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72230.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72232.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72233.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72235.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72240.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72248.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72249.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72250.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72251.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72257.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72261.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72265.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72269.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72273.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72274.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72280.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72291.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72293.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72295.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72305.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72317.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72318.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72327.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72340.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72355.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72357.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72363.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72364.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72365.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72376.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72381.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72387.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72389.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72391.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72393.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72402.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72403.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72405.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72408.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72426.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72440.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72451.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72455.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72456.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72468.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72469.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72476.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72489.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72493.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72501.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72518.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72520.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72528.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72558.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72562.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72572.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72582.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72597.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72632.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72634.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72645.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72649.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72659.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72662.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72672.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72681.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72694.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72698.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72712.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72747.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72764.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72768.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72776.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72786.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72793.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72797.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/72938.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74002.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74004.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74051.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74074.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74090.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74207.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74389.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74455.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74486.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74494.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74530.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74547.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74560.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74606.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74626.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74641.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74646.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74650.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74651.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/74794.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76151.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76225.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76256.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76382.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76394.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76405.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76458.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76595.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76644.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76654.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76679.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76692.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76723.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/76805.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78016.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78073.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78118.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78325.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78355.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78367.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78384.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78397.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78486.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78501.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78526.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78583.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78720.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78730.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78762.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78806.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78861.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78866.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78897.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78970.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/78988.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/80001.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/80035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/80222.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/80241.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/80398.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/80413.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/80447.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/80462.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/81405.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82193.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82280.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82332.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82397.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82400.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82599.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82678.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82765.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82824.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82900.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82965.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/82983.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83208.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83229.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83288.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83362.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83378.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83498.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83566.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83612.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83650.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83746.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83779.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83780.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83827.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83840.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83899.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/83971.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/84008.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/84203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/84628.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/85201.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/85442.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/85469.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/85543.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/85586.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/85799.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/85934.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/86218.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/87047.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/87155.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/87344.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/87418.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/87576.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/87623.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/87715.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/87748.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/87860.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/88889.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/88968.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89001.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89002.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89009.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89022.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89050.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89055.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89512.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89532.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89542.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89564.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89571.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89592.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89606.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89611.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89642.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89662.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89664.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/89671.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91066.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91165.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91212.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91245.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91275.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91285.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91334.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91348.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91366.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91376.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91408.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91413.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91517.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91557.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91592.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91610.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91643.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91680.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91701.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91765.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91801.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91843.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91925.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91938.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91943.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91944.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91948.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91954.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/91958.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/92035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/92044.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/93112.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/93417.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/93780.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/93844.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/93944.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/93986.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/93997.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94014.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94120.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94150.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94170.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94175.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94203.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94238.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94294.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94299.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94300.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94302.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94312.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94326.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94332.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94374.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94403.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94430.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94461.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94510.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94578.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94610.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94637.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94638.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94646.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94647.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94659.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94672.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94711.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94750.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94767.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94776.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94802.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94821.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94865.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94866.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94910.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94975.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94995.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94996.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/94998.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/95527.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96035.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96147.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96163.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96237.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96315.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96413.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96441.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96471.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96481.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96749.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96933.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96935.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/96996.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/97014.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/97072.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/97180.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/97372.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/97560.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/97724.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/97980.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/98223.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/98327.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/98444.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/98618.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/98646.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/98753.dat.gz
wget ftp://ftp.ncdc.noaa.gov./pub/data/igra/derived-v2/data-por/98836.dat.gz
